### ISSUE TITLE
Why aren't you using private PCAPNG block/option codes?

### ISSUE THREAD

**Issue by hadrielk** [HoneProject/Linux-Sensor#15]
Hi,
for the PCAPNG file format, why aren't you setting the MSB bit of the new Block and Option codes you've created, so that they don't collide with future standardized code numbers?  The most significant bit was specifically defined in the PCAPNG format draft to be used for private/local codes, such as this project's use-case.

I ask because I was going to propose using codes 256+257 for a new standardized option code, on the pcap-ng-format mailing list, but found this project was already squatting on those code numbers.  So I'm curious why this project chose them instead of for example 33024 and 33025 (i.e., 256 and 257 with the most significant bit set).  It's not a huge deal - just wondering if there was some reason behind it, so I can understand why others might do something similar.

**Comment by pmoody-** [comment]
That decision predates my involvement with the linux-sensor project, but I have no particular objections to using a more compatible set of options. Can you link to the pcapng documentation that shows what we should be using instead of these?

**Comment by hadrielk** [comment]
No worries - the current version of the draft spec is:
https://tools.ietf.org/html/draft-tuexen-opsawg-pcapng-00

Section 3.1, page 4, is the statement about setting the MSB for the block code, and section 3.5, page 8, says it for the option codes.

**Comment by hashstat** [comment]
At the time we originally wrote Hone, there was no body tracking option numbers. Expecting the values to be picked/requested sequentially, we picked a high value to start from so we, with any luck, wouldn't have to change it later. We intended to officially request the numbers as Hone development took off, but funding went away and development efforts are now limited to volunteers. But the plan was for Hone output to be parseable by Wireshark (and other tools), in which case a private/local value would never do.

**Comment by hadrielk** [comment]
OK cool, I figured it was something like that. Ironically the options I'm adding to the spec happen to be for your use-case: to be able to create new options without requesting allocation from a standards body, but yet be able to have Wireshark/whatever someday decode them. So to do that, we're adding a standards-based option type called "Custom Option", which has its first 4 bytes as a IANA Private Enterprise Number (PEN), which would be your "organization's" PEN, and everything after that is up to you to define/use as you want. (of course an "organization can be an individual, or github project, or whatever)

Getting a PEN is free and trivial and usually gets given out within a day or two (http://pen.iana.org/pen/PenApplication.page).

So once we have this new option code (and a similar thing for Block code), you'll be able to use that without worrying about colliding with other people, and with the ability to have Wireshark/whatever decode it in the future. (by no coincidence, I'm one of the core developers of Wireshark and have a code change coming to add support for these new Custom Options)
