### ISSUE TITLE
Hone stream consumer example

### ISSUE THREAD

**Issue by jikk** [HoneProject/Linux-Sensor#16]
Hi, 

I'm trying to use Hone Linux Sensor to implement IDS like system that listens and monitors online stream. Since Hone's architecture is different from traditional PCAP model by listening to character device of _/dev/hone_, I'm a bit lost where and how to begin. 

Could you provide an example code that listens from _/dev/hone_ and extract connection information instead of writing to a file. 

Thanks a lot for your help in advance!

**Comment by hashstat** [comment]
We don't have any code to dissect the stream; we were using Wireshark for that. I had written a little Python script as well that I used to check Hone output, but I no longer have access to that code.

What you need is a library to parse PCAP-NG. I was able to find a few here on GitHub by searching for pcap-ng. If it  doesn't already have the ability to parse Hone records (and it most likely doesn't), then you will need to add those types (described on the [wiki](https://github.com/HoneProject/Linux-Sensor/wiki/Augmented-PCAP-Next-Generation-Dump-File-Format)).

Alternatively, follow the link in the wiki to the PCAP-NG specification and use it to write your own parser. You could combine it with the hone reader code to produce something that handles the data in real time.

Unfortunately, Hone is no longer being developed, so I wouldn't spend a lot of time writing software around it, unless you are also willing to delve into the kernel code to keep it up-to-date as new kernels are released. Some time ago there was an effort to add similar functionality as a Linux security module. You should probably look into that before continuing to use Hone.

Thanks for checking out Hone!

Brandon

**Comment by craig65535** [comment]
> Some time ago there was an effort to add similar functionality as a Linux security module

Do you know the name of the module?

**Comment by hashstat** [comment]
> Do you know the name of the module?

Unfortunately, I don't. But more importantly, the pieces necessary to write such a module hopefully now exist, where they didn't years ago when we first implemented Hone. So with any luck, there is now a better way to achieve the same or similar results.

**Comment by jikk** [comment]
@hashstat thanks a lot for your reply!

I also had a same question as @craig65535 has. Anyhow, could you be more specific about **the pieces** ? I want to ask around to find out whether the latest kernel implements such a functionality.  If you can also tell me where can I ask this questions (a mailing list or some else place). That will be also very helpful.

Btw, I tried to build Linux_Sensor from Ubuntu 15.10 and got the following error message. 

```
/home/kjee/Linux-Sensor/src/hone_notify_imp.c:300:59: error: ‘struct sock’ has no member named ‘sk_protinfo’
   event->packet.pid = (unsigned long) (args->sk ? args->sk->sk_protinfo : 0);
                                                           ^
scripts/Makefile.build:258: recipe for target '/home/kjee/Linux-Sensor/src/hone_notify_imp.o' failed
make[2]: *** [/home/kjee/Linux-Sensor/src/hone_notify_imp.o] Error 1
Makefile:1398: recipe for target '_module_/home/kjee/Linux-Sensor/src' failed
make[1]: *** [_module_/home/kjee/Linux-Sensor/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-16-generic'
Makefile:138: recipe for target 'modules' failed
```

I assume this is due to some data structure changes in recent kernel source (at least from 4.2.x).
I will try to fix this error and will let you know how it goes.

**Comment by hashstat** [comment]
> ... could you be more specific about **the pieces**?

I can't. A Hone user was, at one time, trying to mainline the Hone features into the kernel and the preferred method was LSM. That is really all I know. I would suggest searching the appropriate kernel mailing list or asking on that list if there is the ability to correlate processes to sockets and/or packets.

As for the build error, there was probably a name change or some other reorganization of the kernel socket structure. I hijacked a field that was unused for IP to store the PID, so hopefully there is still something there to hold that value. Otherwise, the implementation could get kinda messy. Please submit a pull request if you get it working so others can benefit.

I wish I had time to work on this, but not only did funding for that project dry up, but I also changed jobs. And I don't have spare time to devote. Sorry.

**Comment by pmoody-** [comment]
Hey, I was the one who was trying to push this upstream, but I too changed jobs before it happened. if you look for pmoody@google.com on the linux security module list from probably Aug 2014, you'll see the most recent lsm-ified version of hone.

Google actually just recently published the updated module (https://github.com/google/linux-sensor). I haven't spent a lot of time looking at what they released, but I know there are a number of bug fixes and feature enhancements in this code vs what I had published back in 2014.

it doesn't look like it's setup strictly as a fork of this project. Before I left google, I wrote a hone_reader library in c++ with the intention of opensourcing it. It sounds like the current maintainer is interested in writing/releasing a hone_reader library written in go. I'm not sure what his plans are with respect to the c++ library.

**Comment by jikk** [comment]
@pmoody- Thanks a lot for your reply! This is really a helpful information. To me, it might be desirable to have C++ implementation but , as long as a parser implementation exists and it works, it is still a big help to me having at least a reference pointer.  If you know, would you provide me a pointer to a GO implementation? I quickly googled and found the following linke https://github.com/revmischa/gohone but it doesn't seem to be working. 

Thanks a lot for your help!

**Comment by pmoody-** [comment]
there isn't an implementation at this point as far as I'm aware. if and when google does release it, I suspect it'll be on the google github page.

I'd actually suggest opening a feature request on the google linux-sensor project for a c++ or go library for parsing the pcapng.

**Comment by hashstat** [comment]
Thanks for chiming in @pmoody-.
