### ISSUE TITLE
Replacement Project?

### ISSUE THREAD

**Issue by Manouchehri** [HoneProject/Linux-Sensor#17]
I noticed that this project hasn't been active in quite some time after Google took it over; is there any suggested replacements? 

I haven't been able to find anything else that captures the PID in a full network capture on Linux, so any suggestions would be appreciated.

**Comment by hashstat** [comment]
Please see [this comment](16#issuecomment-209019211) from issue #16.

**Comment by Manouchehri** [comment]
Oh, that makes sense. I thought the Google repo wasn't active.

Until they open their ticket tracker here, do you mind if we post here?

**Comment by hashstat** [comment]
> Until they open their ticket tracker here, do you mind if we post here?

What kind of things were you hoping to post? I can answer questions about this project, but it is inactive, so you are unlikely to get a response from anyone else. And I wouldn't expect any response to questions about Google's sensor.

**Comment by Manouchehri** [comment]
@hashstat Do you know who Binbin Peng is? (https://github.com/google/linux-sensor/commits/master?author=binp
)

**Comment by pmoody-** [comment]
I just emailed bin asking him to open up the issue tracker.

**Comment by Manouchehri** [comment]
Thanks!

**Comment by hashstat** [comment]
I know everyone on that list except Binbin Peng, so I assume it is him. Also fits the screen name.

**Comment by Manouchehri** [comment]
Thanks, hopefully he'll be open to continuing the project... no response
yet.

**Comment by craig65535** [comment]
@Manouchehri Cisco has released a kernel module that records socket calls and associates them with PIDs: https://github.com/cisco/ampnetworkflow

It's not a replacement for HONE - it doesn't generate pcap-ng output. However, it can be used to associate network traffic with a PID, so some of the use-cases will overlap.
